# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-27 14:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='sb_Doc',
            fields=[
                ('UT', models.CharField(db_index=True, max_length=30, primary_key=True, serialize=False)),
                ('title', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('PY', models.IntegerField(db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sb_Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True, unique=True, verbose_name='SB Query Title')),
                ('text', models.TextField(null=True, verbose_name='SB Query Text')),
                ('date', models.DateTimeField(verbose_name='SB Query Date')),
                ('r_count', models.IntegerField(null=True, verbose_name='SB Query Results Count')),
            ],
        ),
        migrations.CreateModel(
            name='sb_QueryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True, unique=True, verbose_name='SB Query type name')),
            ],
        ),
        migrations.CreateModel(
            name='sb_SnowballingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True, unique=True, verbose_name='SB Name')),
                ('initial_pearls', models.TextField(null=True, verbose_name='SB Initial Pearls')),
                ('date', models.DateTimeField(verbose_name='SB Date')),
                ('step_count', models.IntegerField(null=True, verbose_name='SB Step Count')),
                ('completed', models.BooleanField(verbose_name='Is SB Completed')),
            ],
        ),
        migrations.CreateModel(
            name='sb_Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepid', models.TextField(null=True, unique=True, verbose_name='SB Step ID')),
                ('date', models.DateTimeField(verbose_name='SB Step Date')),
                ('step_count', models.IntegerField(null=True, verbose_name='SB Step count')),
                ('queries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snowballing.sb_SnowballingSession')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sb_WoSArticle',
            fields=[
                ('doc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='snowballing.sb_Doc')),
                ('ti', models.TextField(null=True, verbose_name='Title')),
                ('ab', models.TextField(null=True, verbose_name='Abstract')),
                ('py', models.IntegerField(null=True, verbose_name='Year')),
                ('ar', models.CharField(max_length=100, null=True, verbose_name='Article Number')),
                ('bn', models.CharField(max_length=100, null=True, verbose_name='ISBN')),
                ('bp', models.CharField(max_length=10, null=True, verbose_name='Beginning Page')),
                ('c1', models.TextField(null=True, verbose_name='Author Address')),
                ('cl', models.TextField(null=True, verbose_name='Conference Location')),
                ('ct', models.TextField(null=True, verbose_name='Conference Title')),
                ('de', models.TextField(null=True, verbose_name='Author Keywords')),
                ('di', models.CharField(max_length=150, null=True, verbose_name='DOI')),
                ('dt', models.CharField(max_length=50, null=True, verbose_name='Document Type')),
                ('em', models.TextField(null=True, verbose_name='E-mail Address')),
                ('ep', models.CharField(max_length=10, null=True, verbose_name='Ending Page')),
                ('fn', models.CharField(max_length=150, null=True, verbose_name='File Name')),
                ('fu', models.TextField(null=True, verbose_name='Funding Agency and Grant Number')),
                ('fx', models.TextField(null=True, verbose_name='Funding Text')),
                ('ga', models.CharField(max_length=100, null=True, verbose_name='Document Delivery Number')),
                ('ho', models.TextField(null=True, verbose_name='Conference Host')),
                ('kwp', models.TextField(null=True, verbose_name='Keywords Plus')),
                ('j9', models.CharField(max_length=30, null=True, verbose_name='29-Character Source Abbreviation')),
                ('ji', models.CharField(max_length=100, null=True, verbose_name='ISO Source Abbreviation')),
                ('la', models.CharField(max_length=100, null=True, verbose_name='Language')),
                ('nr', models.IntegerField(null=True, verbose_name='Cited Reference Count')),
                ('pa', models.TextField(null=True, verbose_name='Publisher Address')),
                ('pd', models.CharField(max_length=10, null=True, verbose_name='Publication Date')),
                ('pg', models.IntegerField(null=True, verbose_name='Page Count')),
                ('pi', models.TextField(null=True, verbose_name='Publisher City')),
                ('pt', models.CharField(max_length=50, null=True, verbose_name='Publication Type')),
                ('pu', models.TextField(null=True, verbose_name='Publisher')),
                ('rp', models.TextField(null=True, verbose_name='Reprint Address')),
                ('sc', models.TextField(null=True, verbose_name='Subject Category')),
                ('se', models.TextField(null=True, verbose_name='Book Series Title')),
                ('si', models.TextField(null=True, verbose_name='Special Issue')),
                ('sn', models.CharField(max_length=80, null=True, verbose_name='ISSN')),
                ('so', models.CharField(max_length=150, null=True, verbose_name='Publication Name')),
                ('sp', models.TextField(null=True, verbose_name='Conference Sponsors')),
                ('su', models.TextField(null=True, verbose_name='Supplement')),
                ('tc', models.IntegerField(null=True, verbose_name='Times Cited')),
                ('vl', models.CharField(max_length=10, null=True, verbose_name='Volume')),
            ],
        ),
        migrations.AddField(
            model_name='sb_snowballingsession',
            name='steps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snowballing.sb_Step'),
        ),
        migrations.AddField(
            model_name='sb_snowballingsession',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sb_query',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snowballing.sb_QueryType'),
        ),
        migrations.AddField(
            model_name='sb_query',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sb_doc',
            name='query',
            field=models.ManyToManyField(to='snowballing.sb_Query'),
        ),
    ]
